application:
  name: drive-core

server:
  port: 8325

spring:
  profiles:
    active: dev

# iwritedb drivedb
datasource:
  url: jdbc:mariadb://192.168.1.104:3306/drivedb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
  driver: org.mariadb.jdbc.Driver
  username: wenyi
  password: 12345678

redis:
  database: 0
  host: 192.168.1.104
  port: 6379
  password: 12345678
  timeout: 50000
  connect-timeout: 10000
  jedis:
    pool:
      max-active: 20
      max-wait: 5000
      max-idle: 10
      min-idle: 0

wxteacher:
  appid: wxc61e3546dba35843
  secret: 3bf72b7330283ff7742ecbaaa40f288a

wxstudent:
  appid: wx0359bc4798d4cb15
  secret: a7c647d9dfd49052c5decd4dbb8176a9

caffeine:
  cache-names: [cachea]
  spec: initialCapacity=50,maximumSize=500,expireAfterAccess=5m

nginx:
  path: D:\ngwww\driveupload

rabbitmq:
  host: 192.168.1.104
  port: 5672
  virtualHost: "/"
  username: admin
  password: 12345678
